# This is a basic workflow to help you get started with Actions

name: CI/CD master

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
